---
jobs:
    test:
        image: node:6
        steps:
           # - rm_git: rm -rf /hab/pkgs/core/git
           # - test_git: echo Cloning github.com/minz1027/waffle, on branch master && if [ ! -z $SCM_CLONE_TYPE ] && [ $SCM_CLONE_TYPE = ssh ]; then export SCM_URL=git@github.com:minz1027/waffle; elif [ ! -z $SCM_USERNAME ] && [ ! -z $SCM_ACCESS_TOKEN ]; then export SCM_URL=https://$SCM_USERNAME:$SCM_ACCESS_TOKEN@github.com/minz1027/waffle; else export SCM_URL=https://github.com/minz1027/waffle; fi && sd-step exec core/git "git clone --quiet --progress --branch master $SCM_URL /tmp/test" && sd-step exec core/git "git reset --hard f24b001a58983209e04bb90612ec5c457b8d074d" && echo Reset to f24b001a58983209e04bb90612ec5c457b8d074d && echo Setting user name and user email && sd-step exec core/git "git config user.name sd-buildbot" && sd-step exec core/git "git config user.email dev-null@screwdriver.cd"
           # - test_hab: sd-step exec core/redis "redis-cli --version"
            - echo: echo hello

