
jobs:
    main:
        annotations:
            screwdriver.cd/collapseBuilds: false
        requires: [~commit, ~pr, ~sd@365:no_main]
        image: screwdrivercd/launcher
        steps:
           - sleep: meta get build.buildId

