
jobs:
    main:
#        annotations:
#            screwdriver.cd/buildPeriodically: '35 * * * *'
        requires: [~commit, ~pr, ~sd@365:no_main]
        image: node:8
        steps:
           - sleep: sleep 60

